apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: deploycat-db
  namespace: deploycat-system
spec:
  instances: 3
  bootstrap:
    initdb:
      database: deploycat
      owner: deploycat
      # secret:
      #   name: app-db
  storage:
    storageClass: longhorn
    size: 1Gi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploycat
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploycat-binding
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploycat # name of role
subjects: # points to my ServiceAccount
  - kind: ServiceAccount
    name: app # service account to bind to
    namespace: deploycat-system # ns of service account

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: deploycat-system

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app
  namespace: deploycat-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      serviceAccountName: app
      containers:
        - name: app
          image: ghcr.io/deploy-cat/deploy-cat-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: DEPLOYCAT_KUBECONFIG_FROM_CLUSTER
              value: "true"
            - name: DEPLOYCAT_PROMETHEUS_URL
              value: "http://prometheus-47978363-kube-p-prometheus.deploycat-system.svc.cluster.local:9090"
            - name: DEPLOYCAT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: deploycat-db-app
                  key: uri
