version: "3"

services:
  mongodb:
    image: mongo:6.0
    env_file: .env
  app:
    image: node:alpine
    env_file: .env
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - 3000:3000
