version: "3"

services:
  db:
    image: "postgres"
    ports:
      - 15432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: deploycat
      POSTGRES_USER: deploycat
      POSTGRES_PASSWORD: deploycat
  app:
    image: node:alpine
    env_file: .env
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - 3000:3000
