apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploycat-web.fullname" . }}-app
  labels:
  {{- include "deploycat-web.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.app.serviceAccount.annotations | nindent 4 }}