global:
  # storageClass:
app:
  serviceAccount:
    annotations: {}
  scale:
    min: 1
kubernetesClusterDomain: cluster.local
postgresql:
  enabled: true
  auth:
    username: deploycat
    password: deploycat
    database: deploycat
